# Generated by Django 4.2.4 on 2023-10-18 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_project_options_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
