# Generated by Django 4.2.4 on 2023-10-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_delete_message"),
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chat",
            new_name="Room",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="chat",
            new_name="room",
        ),
        migrations.AlterField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
