# Generated by Django 4.2.4 on 2023-10-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_rename_chat_room_rename_chat_message_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="something", max_length=255),
            preserve_default=False,
        ),
    ]
