# Generated by Django 4.2.4 on 2023-10-10 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_location_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="social_instagram",
            new_name="social_stackoverflow",
        ),
    ]
