# Generated by Django 4.2.4 on 2023-10-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_social_instagram_profile_social_stackoverflow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="owner",
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(related_name="profiles", to="users.skill"),
        ),
    ]
