# Generated by Django 4.2.4 on 2023-10-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
