# Generated by Django 4.2.4 on 2023-10-19 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_message_read_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
